#!/usr/bin/env python3
"""Generate the Navigator mod's data tables from the Python runtime (TASK-84).

Python stays the source of truth until v9: config defaults, sentinel tags and budget
clamps are emitted as TypeScript under hooks/mod/lib/gen/ so the mod never hand-copies
them. Parity fixtures (Python outputs for a fixed corpus) are emitted under
hooks/mod/tests/fixtures/ so kit tests can compare the TS ports byte for byte.

    python3 scripts/gen_mod_data.py          # write
    python3 scripts/gen_mod_data.py --check  # exit 1 when any generated file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "hooks"))

import re  # noqa: E402

from nav_hook_lib import budget, config, judge, scoring, sentinels  # noqa: E402

HEADER = "// GENERATED by scripts/gen_mod_data.py from the Python runtime. Do not edit.\n"


def ts_const(name: str, value, type_ann: str = "", compact: bool = False) -> str:
    """`compact` for large fixtures: the mod test kit refuses imports over 1 MiB."""
    body = json.dumps(value, ensure_ascii=False, separators=(",", ":")) if compact \
        else json.dumps(value, indent=2, ensure_ascii=False)
    if type_ann:  # large fixtures: an explicit row type, no `as const` (TS union blow-up)
        return f"export const {name}: {type_ann} = {body}\n"
    return f"export const {name} = {body} as const\n"


def config_defaults() -> str:
    return HEADER + "\n" + ts_const("CONFIG_DEFAULTS", config.DEFAULTS)


def sentinel_data() -> str:
    return (HEADER + "\n" + ts_const("TAGS", sentinels.TAGS)
            + "\n" + ts_const("BUDGETS", budget.BUDGETS)
            + "\n" + ts_const("TRUNCATION_MARKER", budget.TRUNCATION_MARKER))


STRIP_CORPUS = [
    "",
    "plain prompt with no sentinels",
    "<nav-workflow-block>\nrun until done\n</nav-workflow-block>\nreal question",
    "before <nav-read-guard-block>x</nav-read-guard-block> after",
    "<!-- nav-session-start-injected:v1 -->\n# Navigator Session Start\nbody",
    "orphan open <nav-workflow-block> only",
    "orphan close </nav-workflow-block> only",
    "<nav-workflow-block>a</nav-workflow-block>\nOriginal prompt: keep going\nnext",
    "Original prompt: survives without sentinels",
    "<nav-workflow-block>\nmulti\nline\n</nav-workflow-block><nav-workflow-block>b</nav-workflow-block>",
]


def clamp_corpus():
    line = "x" * 120
    cases = []
    for event in ("SessionStart", "SubagentStart", "UserPromptSubmit"):
        for n in (0, 1, 10, 80, 120):
            cases.append((event, "\n".join([line] * n)))
        cases.append((event, "y" * 12000))
        # astral code points: Python len() counts one per emoji, JS .length counts two
        cases.append((event, ("🧭 nav " * 1500) + "\nend"))
        cases.append((event, "\n".join(["é😀" * 60] * 90)))
    return cases


def parity_fixtures() -> str:
    strip = [{"input": t, "output": sentinels.strip_all(t)} for t in STRIP_CORPUS]
    clamp = [{"event": e, "input": t, "output": budget.clamp(t, e)} for e, t in clamp_corpus()]
    return (HEADER + "\n" + ts_const("STRIP_CASES", strip)
            + "\n" + ts_const("CLAMP_CASES", clamp))


def scoring_data() -> str:
    tables = {
        "LOOP_TRIGGERS": scoring.LOOP_TRIGGERS,
        "COMPLEXITY_INDICATORS": scoring.COMPLEXITY_INDICATORS,
        "MULTI_FILE_INDICATORS": scoring.MULTI_FILE_INDICATORS,
        "QUESTION_STARTERS": sorted(scoring.QUESTION_STARTERS),
        "CONFIRMATION_PREFIXES": scoring.CONFIRMATION_PREFIXES,
        "CONFIRMATION_MAX_WORDS": scoring.CONFIRMATION_MAX_WORDS,
        "TASK_SHAPED_VERBS": scoring.TASK_SHAPED_VERBS,
        "VAGUE_SCOPE_SIGNALS": scoring.VAGUE_SCOPE_SIGNALS,
        "LIMITER_WORDS": scoring.LIMITER_WORDS,
        "ACCEPTANCE_PHRASES": scoring.ACCEPTANCE_PHRASES,
        "APPROACH_CONNECTORS": scoring.APPROACH_CONNECTORS,
        "AMBIGUITY_DIMENSIONS": list(scoring.AMBIGUITY_DIMENSIONS),
        "SCORES": {
            "BASE_SCORE": scoring.BASE_SCORE, "VAGUE_BONUS": scoring.VAGUE_BONUS,
            "CREDIT_FILE_PATH": scoring.CREDIT_FILE_PATH, "CREDIT_NUMBER": scoring.CREDIT_NUMBER,
            "CREDIT_LIMITER": scoring.CREDIT_LIMITER, "CREDIT_ACCEPTANCE": scoring.CREDIT_ACCEPTANCE,
        },
        "JUDGE_LOOP_PHRASE": scoring.JUDGE_LOOP_PHRASE,
    }
    return HEADER + "\n" + "\n".join(ts_const(k, v) for k, v in tables.items())


def _test_prompts() -> list:
    """Prompts the Python op/scoring tests already exercise (committed test files only)."""
    found = []
    for path in sorted((ROOT / "hooks").rglob("test_*.py")):
        text = path.read_text(encoding="utf-8")
        found += re.findall(r'ctx\("((?:[^"\\]|\\.){1,200})"', text)
        found += re.findall(r'(?:score_ambiguity|detect_workflow|score)\("((?:[^"\\]|\\.){1,200})"',
                            text)
    return found


def scoring_corpus() -> list:
    evals = json.loads((ROOT / "hooks/nav_hook_lib/fixtures/judge_eval.json").read_text())
    base = [p["text"] for p in evals["prompts"]] + _test_prompts()
    base += [
        "", "   ", "?", "yes", "ok go ahead", "no, stop", "lgtm", "sounds good to me",
        "How does auth work?", "what's next", "Refactor hooks/ops/prompt_gate.py only",
        "fix 3 bugs in the api", "update everything until done", "don't stop until finished",
        "do all the things", "addresses and installers", "modifying the module",
        "set   up the ci", "clean\tup the tests", "implement it using the judge",
        "verify with make test", "build the app; acceptance criteria: green CI",
        "Füge Tests hinzu und fix the café module", "fix naïve_parser.py", "update ünïcode/ path",
        "refactor ２ files", "fix the bug in módulo.ts", "İmplement the İ feature",
        "<nav-workflow-block>\nrun until done\n</nav-workflow-block>\nfix the login",
        "Run Until Done", "KEEP GOING!", "keep-going", "keep_going", "iterate until green",
        "loop mode on", "autonomous mode please", "finish this now", "complete everything",
        "migrate the db across all files", "project-wide rename", "change all imports",
    ]
    seen, out = set(), []
    for t in base:
        for v in (t, t.upper(), t.lower() + ".", "please " + t, t + " now?", t.replace(" ", "  ")):
            if v not in seen:
                seen.add(v)
                out.append(v)
    return out


def scoring_fixtures() -> str:
    cases = []
    for t in scoring_corpus():
        cases.append({
            "prompt": t,
            "workflow": scoring.detect_workflow(t),
            "ambiguity": scoring.score_ambiguity(t),
        })
    return HEADER + "\n" + ts_const("SCORING_CASES", cases, "ReadonlyArray<{ prompt: string; workflow: unknown; ambiguity: unknown }>", compact=True)


def judge_data() -> str:
    tables = {
        "JUDGE_DEFAULTS": judge.DEFAULTS,
        "QUESTIONS": judge.QUESTIONS,
        "COMPLEXITY_LEVELS": list(judge.COMPLEXITY_LEVELS),
        "AMBIGUITY_LEVELS": list(judge.AMBIGUITY_LEVELS),
        "AMBIGUITY_WEIGHTS": list(judge.AMBIGUITY_WEIGHTS),
        "DIMENSIONS": list(judge.DIMENSIONS),
        "REDACTED": judge.REDACTED,
    }
    return HEADER + "\n" + "\n".join(ts_const(k, v) for k, v in tables.items())


REDACT_CORPUS = [
    "plain text", "api_key = abc123XYZ", "TOKEN: 'ghp_aaaaaaaaaaaaaaaaaaaaaaaa'", "password=hunter2 ok",
    "use sk-abcdefghijklmnopqrstuv now", "ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123",
    "AKIAABCDEFGHIJKLMNOP", "xoxb-1234567890-abc", "apikey_ABCDEFGHIJKLMNOPQR",
    "jwt eyJhbGciOiJIUzI1.eyJzdWIiOiIxMjM0.SflKxwRJSMeKKF2QT4", "sha " + "a" * 40,
    "Bearer: tokenvalue123", "café secret: naïve", "notakey=value",
]


def judge_fixtures() -> str:
    evals = json.loads((ROOT / "hooks/nav_hook_lib/fixtures/judge_eval.json").read_text())["prompts"]
    recorded = json.loads((ROOT / "hooks/nav_hook_lib/fixtures/judge_eval_recorded.json").read_text())
    settings = judge.settings({})
    thresholds = judge._thresholds(settings)
    cases = []
    for prompt, rec in zip(evals, recorded):
        text = prompt["text"]
        j = judge.parse_response(rec["_doc"], thresholds)
        j.latency_ms = int(rec.get("_latency_ms") or 0)
        cases.append({
            "prompt": text,
            "doc": rec["_doc"],
            "latency_ms": j.latency_ms,
            "request": judge.build_request(text, settings),
            "verdicts": {
                "task": j.task_verdict(), "loop": j.loop_verdict(),
                "complexity": j.complexity_if_confident(), "level": j.complexity_level(),
                "ambiguity": j.ambiguity_if_confident(),
                "dimensions": {d: j.dimension_verdict(d) for d in judge.DIMENSIONS},
            },
            "workflow": scoring.detect_workflow(text, judgment=j),
            "ambiguity": scoring.score_ambiguity(text, judgment=j),
        })
    redact = [{"input": t, "output": judge.redact_secrets(t)} for t in REDACT_CORPUS]
    return HEADER + "\n" + ts_const("JUDGE_CASES", cases, "ReadonlyArray<{ prompt: string; doc: Record<string, unknown>; latency_ms: number; request: unknown; verdicts: unknown; workflow: unknown; ambiguity: unknown }>", compact=True) + "\n" + ts_const("REDACT_CASES", redact)


OP_VARIANTS = [
    {"name": "defaults", "patch": {}},
    {"name": "lenient", "patch": {"workflow_enforcer_hook": {"strict_block": False},
                                  "task_mode": {"enabled": False}}},
    {"name": "brief-tight", "patch": {"brief_hook": {"ambiguity_threshold": 0.3,
                                                     "contradiction_field": False}}},
]


def op_fixtures(only: str) -> str:
    """Python op results for prompt_gate / prompt_brief, judge off, no graph (recall '').

    One file per config variant: the mod test kit refuses imports over 1 MiB."""
    import copy
    import tempfile
    import types
    sys.path.insert(0, str(ROOT / "hooks" / "ops"))
    import prompt_brief  # noqa: E402
    import prompt_gate  # noqa: E402

    prompts = scoring_corpus()[:400]
    variants = [v for v in OP_VARIANTS if v["name"] == only]
    cases = []
    with tempfile.TemporaryDirectory() as tmp:
        for variant in variants:
            cfg = config.DEFAULTS
            cfg = json.loads(json.dumps(cfg))
            for k, v in variant["patch"].items():
                cfg.setdefault(k, {}).update(v)
            for check in (True, False, None):
                state = {"turn": {"signals": {"check_shown": check}}}
                for text in prompts:
                    ctx = types.SimpleNamespace(
                        event="UserPromptSubmit", payload={"prompt": text, "cwd": tmp},
                        config=cfg, state=copy.deepcopy(state), pilot_executor=False, now=0.0)
                    gate = prompt_gate.run(ctx)
                    brief = prompt_brief.run(ctx) if check is None else None
                    cases.append({"variant": variant["name"], "check": check, "prompt": text,
                                  "gate": gate, "brief": brief})
    return HEADER + "\n" + ts_const("OP_CASES", cases, "ReadonlyArray<{ variant: string; check: boolean | null; prompt: string; gate: unknown; brief: unknown }>", compact=True)


def op_variants() -> str:
    return HEADER + "\n" + ts_const("OP_VARIANTS", OP_VARIANTS)


TIER1_GRAPH = {
    "version": "1.0.0", "last_updated": "2026-10-02T08:00:39+00:00",
    "stats": {"total_nodes": 195, "total_edges": 843, "memory_count": 71},
    "concept_index": {"hooks": [], "mods": [], "state": []},
}
TIER1_MARKERS = [f"2026-10-{d:02d}-marker.md" for d in range(1, 13)]


def tier1_fixtures() -> str:
    """Python prompt_tier1 results and the state sections it leaves behind."""
    import copy
    import tempfile
    import types
    sys.path.insert(0, str(ROOT / "hooks" / "ops"))
    import prompt_tier1  # noqa: E402

    variants = {
        "on": {"tier1": {"enabled": True}, "version": "7.9.0"},
        "nav-stats-off": {"tier1": {"enabled": True, "rules": {"nav_stats": False}}},
        "off": {"tier1": {"enabled": False}},
        "drift": {"tier1": {"enabled": True}, "version": "7.1.0"},
    }
    prompts = ["nav stats", "NAV STATS", "  show features ", "list markers", "graph health",
               "nav version", "nav stats please", "stats nav", "graph", "show me the features",
               "<!-- nav-session-start-injected:v1 -->\nnav version", "x" * 60, "", "list  markers"]
    priors = [{}, {"turn": {"tier1_hit": "nav_stats"}, "tier1": {"hits": 3, "false_positives": 1}},
              {"reads": {"turn_count": 4}, "judge": {"calls": 2, "failed": 1, "latency_last_ms": 300,
               "latency_max_ms": 700, "axes": {"loop": {"agreed": 2}, "task": {"overridden": 1}}},
               "meta": {"op_errors": [{"op": "x"}]}}]
    cases = []
    with tempfile.TemporaryDirectory() as tmp:
        agent = Path(tmp) / ".agent"
        (agent / "knowledge").mkdir(parents=True)
        (agent / "knowledge" / "graph.json").write_text(json.dumps(TIER1_GRAPH))
        (agent / ".context-markers").mkdir()
        for name in TIER1_MARKERS:
            (agent / ".context-markers" / name).write_text("m")
        for vname, patch in variants.items():
            cfg = json.loads(json.dumps(config.DEFAULTS))
            for k, v in patch.items():
                if isinstance(v, dict):
                    cfg.setdefault(k, {}).update(v)
                else:
                    cfg[k] = v
            for prior in priors:
                for text in prompts:
                    state = copy.deepcopy(prior)
                    ctx = types.SimpleNamespace(
                        event="UserPromptSubmit", payload={"prompt": text, "cwd": tmp},
                        config=cfg, state=state, pilot_executor=False, now=0.0)
                    result = prompt_tier1.run(ctx)
                    cases.append({"variant": vname, "prior": prior, "prompt": text,
                                  "result": result, "after": state})
    manifest = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
    return (HEADER + "\n" + ts_const("TIER1_VARIANTS", variants) + "\n"
            + ts_const("TIER1_GRAPH", TIER1_GRAPH) + "\n" + ts_const("TIER1_MARKERS", TIER1_MARKERS)
            + "\n" + ts_const("PLUGIN_VERSION", manifest["version"]) + "\n"
            + ts_const("TIER1_CASES", cases, "ReadonlyArray<{ variant: string; prior: Record<string, unknown>; "
                       "prompt: string; result: unknown; after: Record<string, unknown> }>", compact=True))


TARGETS = {
    ROOT / "hooks/mod/tests/fixtures/tier1.gen.ts": tier1_fixtures,
    ROOT / "hooks/mod/tests/fixtures/ops-variants.gen.ts": op_variants,
    ROOT / "hooks/mod/tests/fixtures/ops-defaults.gen.ts": lambda: op_fixtures("defaults"),
    ROOT / "hooks/mod/tests/fixtures/ops-lenient.gen.ts": lambda: op_fixtures("lenient"),
    ROOT / "hooks/mod/tests/fixtures/ops-brief-tight.gen.ts": lambda: op_fixtures("brief-tight"),
    ROOT / "hooks/mod/lib/gen/judge-data.gen.ts": judge_data,
    ROOT / "hooks/mod/tests/fixtures/judge.gen.ts": judge_fixtures,
    ROOT / "hooks/mod/lib/gen/scoring-data.gen.ts": scoring_data,
    ROOT / "hooks/mod/tests/fixtures/scoring.gen.ts": scoring_fixtures,
    ROOT / "hooks/mod/lib/gen/config-defaults.gen.ts": config_defaults,
    ROOT / "hooks/mod/lib/gen/sentinels.gen.ts": sentinel_data,
    ROOT / "hooks/mod/tests/fixtures/foundation.gen.ts": parity_fixtures,
}


def _plugin_targets() -> dict:
    """Extra targets from scripts/mod_fixtures/*.py, each defining TARGETS {path: build}.

    Lets op groups ship their own fixture builders without editing this file. Builders may
    use this module's helpers via ``import gen_mod_data as g`` (HEADER, ts_const, config...).
    """
    extra = {}
    folder = ROOT / "scripts" / "mod_fixtures"
    sys.path.insert(0, str(ROOT / "scripts"))
    for path in sorted(folder.glob("*.py")):
        if path.name.startswith("_"):
            continue
        name = f"mod_fixtures.{path.stem}"
        module = __import__(name, fromlist=["TARGETS"])
        extra.update(getattr(module, "TARGETS", {}))
    return extra


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    stale = []
    for path, build in {**TARGETS, **_plugin_targets()}.items():
        text = build()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale generated files (run scripts/gen_mod_data.py):\n  " + "\n  ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
