#!/usr/bin/env python3
"""Generate the Navigator mod's data tables from the Python runtime (TASK-84).

Python stays the source of truth until v9: config defaults, sentinel tags and budget
clamps are emitted as TypeScript under hooks/mod/lib/gen/ so the mod never hand-copies
them. Parity fixtures (Python outputs for a fixed corpus) are emitted under
hooks/mod/tests/fixtures/ so kit tests can compare the TS ports byte for byte.

    python3 scripts/gen_mod_data.py          # write
    python3 scripts/gen_mod_data.py --check  # exit 1 when any generated file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "hooks"))

from nav_hook_lib import budget, config, sentinels  # noqa: E402

HEADER = "// GENERATED by scripts/gen_mod_data.py from the Python runtime. Do not edit.\n"


def ts_const(name: str, value, type_ann: str = "") -> str:
    body = json.dumps(value, indent=2, ensure_ascii=False)
    ann = f": {type_ann}" if type_ann else ""
    return f"export const {name}{ann} = {body} as const\n"


def config_defaults() -> str:
    return HEADER + "\n" + ts_const("CONFIG_DEFAULTS", config.DEFAULTS)


def sentinel_data() -> str:
    return (HEADER + "\n" + ts_const("TAGS", sentinels.TAGS)
            + "\n" + ts_const("BUDGETS", budget.BUDGETS)
            + "\n" + ts_const("TRUNCATION_MARKER", budget.TRUNCATION_MARKER))


STRIP_CORPUS = [
    "",
    "plain prompt with no sentinels",
    "<nav-workflow-block>\nrun until done\n</nav-workflow-block>\nreal question",
    "before <nav-read-guard-block>x</nav-read-guard-block> after",
    "<!-- nav-session-start-injected:v1 -->\n# Navigator Session Start\nbody",
    "orphan open <nav-workflow-block> only",
    "orphan close </nav-workflow-block> only",
    "<nav-workflow-block>a</nav-workflow-block>\nOriginal prompt: keep going\nnext",
    "Original prompt: survives without sentinels",
    "<nav-workflow-block>\nmulti\nline\n</nav-workflow-block><nav-workflow-block>b</nav-workflow-block>",
]


def clamp_corpus():
    line = "x" * 120
    cases = []
    for event in ("SessionStart", "SubagentStart", "UserPromptSubmit"):
        for n in (0, 1, 10, 80, 120):
            cases.append((event, "\n".join([line] * n)))
        cases.append((event, "y" * 12000))
    return cases


def parity_fixtures() -> str:
    strip = [{"input": t, "output": sentinels.strip_all(t)} for t in STRIP_CORPUS]
    clamp = [{"event": e, "input": t, "output": budget.clamp(t, e)} for e, t in clamp_corpus()]
    return (HEADER + "\n" + ts_const("STRIP_CASES", strip)
            + "\n" + ts_const("CLAMP_CASES", clamp))


TARGETS = {
    ROOT / "hooks/mod/lib/gen/config-defaults.gen.ts": config_defaults,
    ROOT / "hooks/mod/lib/gen/sentinels.gen.ts": sentinel_data,
    ROOT / "hooks/mod/tests/fixtures/foundation.gen.ts": parity_fixtures,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    stale = []
    for path, build in TARGETS.items():
        text = build()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale generated files (run scripts/gen_mod_data.py):\n  " + "\n  ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
