// GENERATED by scripts/gen_mod_data.py from the Python runtime. Do not edit.

export const OP_VARIANTS = [
  {
    "name": "defaults",
    "patch": {}
  },
  {
    "name": "lenient",
    "patch": {
      "workflow_enforcer_hook": {
        "strict_block": false
      },
      "task_mode": {
        "enabled": false
      }
    }
  },
  {
    "name": "brief-tight",
    "patch": {
      "brief_hook": {
        "ambiguity_threshold": 0.3,
        "contradiction_field": false
      }
    }
  }
] as const
