// GENERATED by scripts/gen_mod_data.py from the Python runtime. Do not edit.

export const REJECT_LINES = [
  {
    "ts": "2026-10-05T09:06:06.895917+00:00",
    "session": "s1",
    "event": "Stop",
    "op": "stop_completion",
    "tool": null,
    "suppressed": false,
    "reject": {
      "reason": "mutating turn, 1/6 indicators met, no exit signal",
      "evidence": {
        "met": 1,
        "unmet": [
          "code_committed",
          "tests_passing"
        ],
        "mutating_tools": [
          "Bash"
        ]
      }
    },
    "line": "{\"ts\":\"2026-10-05T09:06:06.895917+00:00\",\"session\":\"s1\",\"event\":\"Stop\",\"op\":\"stop_completion\",\"reason\":\"mutating turn, 1/6 indicators met, no exit signal\",\"evidence\":{\"met\":1,\"unmet\":[\"code_committed\",\"tests_passing\"],\"mutating_tools\":[\"Bash\"]}}"
  },
  {
    "ts": "2026-10-05T09:06:06+00:00",
    "session": "s1",
    "event": "PreToolUse",
    "op": "read_guard",
    "tool": "Read",
    "suppressed": false,
    "reject": {
      "reason": "5 .agent/ reads this turn (escalate_threshold=5)",
      "evidence": {
        "path": "tasks/TASK-88-reject-log.md",
        "count": 5,
        "threshold": 5
      }
    },
    "line": "{\"ts\":\"2026-10-05T09:06:06+00:00\",\"session\":\"s1\",\"event\":\"PreToolUse\",\"op\":\"read_guard\",\"tool\":\"Read\",\"reason\":\"5 .agent/ reads this turn (escalate_threshold=5)\",\"evidence\":{\"path\":\"tasks/TASK-88-reject-log.md\",\"count\":5,\"threshold\":5}}"
  },
  {
    "ts": "2026-10-05T09:06:06+00:00",
    "session": null,
    "event": "UserPromptSubmit",
    "op": "prompt_gate",
    "tool": null,
    "suppressed": true,
    "reject": {
      "reason": "loop trigger after a skipped WORKFLOW CHECK (strict_block)",
      "evidence": {
        "trigger": "run until done"
      }
    },
    "line": "{\"ts\":\"2026-10-05T09:06:06+00:00\",\"session\":null,\"event\":\"UserPromptSubmit\",\"op\":\"prompt_gate\",\"reason\":\"loop trigger after a skipped WORKFLOW CHECK (strict_block)\",\"evidence\":{\"trigger\":\"run until done\"},\"suppressed\":true}"
  },
  {
    "ts": "T",
    "session": "s",
    "event": "Stop",
    "op": "x",
    "tool": "",
    "suppressed": false,
    "reject": {},
    "line": "{\"ts\":\"T\",\"session\":\"s\",\"event\":\"Stop\",\"op\":\"x\",\"reason\":\"\",\"evidence\":{}}"
  },
  {
    "ts": "T",
    "session": "s",
    "event": "Stop",
    "op": "x",
    "tool": null,
    "suppressed": false,
    "reject": {
      "reason": "quotes \" and \\ and unicode — café",
      "evidence": {
        "nested": {
          "a": [
            1,
            2,
            {
              "b": null
            }
          ]
        },
        "flag": true
      }
    },
    "line": "{\"ts\":\"T\",\"session\":\"s\",\"event\":\"Stop\",\"op\":\"x\",\"reason\":\"quotes \\\" and \\\\ and unicode — café\",\"evidence\":{\"nested\":{\"a\":[1,2,{\"b\":null}]},\"flag\":true}}"
  },
  {
    "ts": "T",
    "session": "s",
    "event": "Stop",
    "op": "x",
    "tool": null,
    "suppressed": false,
    "reject": {
      "reason": "control chars \t\n\u0001",
      "evidence": "not-a-dict"
    },
    "line": "{\"ts\":\"T\",\"session\":\"s\",\"event\":\"Stop\",\"op\":\"x\",\"reason\":\"control chars \\t\\n\\u0001\",\"evidence\":{}}"
  }
] as const
